import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:shared_preferences/shared_preferences.dart';

class PrivacyPolicyScreen extends StatelessWidget {
  final bool showConsentActions;

  const PrivacyPolicyScreen({
    super.key,
    this.showConsentActions = false,
  });

  Future<void> _acceptPolicy(BuildContext context) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool('has_accepted_policy', true);
    if (context.mounted) {
      Navigator.of(context).pushReplacementNamed('/main');
    }
  }

  void _declinePolicy() {
    SystemNavigator.pop();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Privacy Policy'),
        centerTitle: true,
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          children: [
            const Expanded(
              child: SingleChildScrollView(
                child: Text(
                  '''Last updated: October 26, 2023

This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.

We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.

Interpretation and Definitions
============================

Interpretation
--------------

The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.

Definitions
-----------

For the purposes of this Privacy Policy:

* Account means a unique account created for You to access our Service or parts of our Service.

* Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to XapZap.

* Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.

* Country refers to: New York, United States

* Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.

* Personal Data is any information that relates to an identified or identifiable individual.

* Service refers to the Application.

* Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.

* Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).

* You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
                  ''',
                ),
              ),
            ),
            const SizedBox(height: 16),
            if (showConsentActions)
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                children: [
                  ElevatedButton(
                    onPressed: _declinePolicy,
                    style: ElevatedButton.styleFrom(
                      backgroundColor: Colors.red,
                    ),
                    child: const Text('Decline'),
                  ),
                  ElevatedButton(
                    onPressed: () => _acceptPolicy(context),
                    child: const Text('Accept'),
                  ),
                ],
              ),
          ],
        ),
      ),
    );
  }
}
